# Generated by Django 4.2.7 on 2023-11-27 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_patient_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='password',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='username',
        ),
    ]
