# Generated by Django 4.2.7 on 2023-11-27 22:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_remove_patient_password_remove_patient_username'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='nurseschedules',
            options={},
        ),
    ]
