# Generated by Django 4.2.7 on 2023-11-28 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_nurse_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeSlot',
            fields=[
                ('id', models.IntegerField(db_column='id', primary_key=True, serialize=False)),
                ('time', models.DateTimeField(db_column='time')),
                ('num_patients', models.CharField(db_column='Num_patients', max_length=45)),
                ('num_nurses', models.CharField(db_column='Num_nurses', max_length=45)),
            ],
            options={
                'db_table': 'time_slot',
            },
        ),
    ]
