# Generated by Django 4.2.7 on 2023-11-28 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_timeslot'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientSchedule',
            fields=[
                ('id', models.IntegerField(db_column='id', primary_key=True, serialize=False)),
                ('time_slot', models.DateTimeField(db_column='Time_slot')),
                ('patient_ssn', models.CharField(db_column='Patient_SSN', max_length=15)),
                ('vaccine', models.CharField(db_column='Vaccine', max_length=50)),
            ],
            options={
                'db_table': 'patient_schedule',
            },
        ),
    ]
