# Generated by Django 4.2.7 on 2023-11-28 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0010_patientschedule'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PatientSchedule',
        ),
    ]
